apps/models.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:50' 

from flask_sqlalchemy import SQLAlchemy
from apps import db
from datetime import datetime

class News(db.Model):
    __tablename__ = "news"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.String(2000), nullable=False)
    types = db.Column(db.String(10), nullable=False)
    img_url = db.Column(db.String(300))
    author = db.Column(db.String(20))
    view_count = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now)
    is_valid = db.Column(db.Boolean,default=0)

    def __str__(self):
        return self.title


    def to_dict(self):
        return dict(title=self.title, content=self.content,
                    news_type=self.types, img_url=self.image, author=self.author,
                    view_count=self.view_count, created_at=self.created_at)

apps/admin/forms.py
#!/usr/bin/python
#coding=utf-8


from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SubmitField, SelectField, RadioField
from wtforms.validators import DataRequired

class NewsForm(FlaskForm):
    """ 新闻表单 """
    title = StringField(label='新闻标题', validators=[DataRequired("请输入标题")],
        description="请输入标题",
        render_kw={"required": "required", "class": "form-control"})
    content = TextAreaField(label='新闻内容', validators=[DataRequired("请输入内容")],
        description="请输入内容",
        render_kw={"required": "required", "class": "form-control"})
    types = SelectField('新闻类型',
        choices=[('推荐', '推荐'), ('百家', '百家'), ('本地', '本地'), ('图片', '图片')],
        render_kw={"class": "form-control"})
    # img_url = StringField(label='新闻图片',
    #     description='请输入图片地址',
    #     render_kw={'required': 'required', 'class': 'form-control'})
    img_url = FileField(label='新闻图片',
        description='请输入图片地址',
        render_kw={'required': 'required', 'class': 'form-control'})
    submit = SubmitField('提交', render_kw={
        'class':'btn-success'
    })

apps/__init__.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:14' 

import os
from flask  import Flask, render_template, redirect, url_for

from apps.home import front  as home_blueprint
from apps.admin import backend  as admin_blueprint


#基于Flask创建的application
app = Flask(__name__)


#（1）注册各个模块子蓝图到app上
app.register_blueprint(home_blueprint, url_prefix="/home")
app.register_blueprint(admin_blueprint, url_prefix="/admin")

############ SQL Alchemy Settings start############
from flask_sqlalchemy import SQLAlchemy
mysql_conn_str = \
	"mysql+pymysql://zhougy:123456@192.168.51.81:3306/flask_news?charset=utf8"

#配置数据库连接，secret_key, 上传文件路径UP_DIR, 到app
app.config["SQLALCHEMY_DATABASE_URI"] = mysql_conn_str
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] =  True

app.config['SECRET_KEY'] = 'this is the 1000phone flask secret key'

#文件上传配置
app.config['UP_DIR'] = os.path.join(os.path.abspath(os.path.dirname(__file__)),
									"static/img/news/")

#基于app来创建SQLAlchemy 数据库操作实例db
db  = SQLAlchemy(app)

from apps import models

############ SQL Alchemy Settings end############

@app.route('/')
def index():
	return redirect(url_for("home.index"))

apps/admin/__init__.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:19' 


from flask import Blueprint, redirect

backend = Blueprint("admin", __name__)

import apps.admin.views

@backend.route('/', methods = ("GET", ))
def admin_home():
	return redirect('/admin/index/')

apps/admin/views.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:49' 

from flask import Response, render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from datetime import datetime
from . import backend


#修改文件名称
def change_filename(filename):
    import os, uuid
    fileinfo = os.path.splitext(filename)
    #filename = datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    #return filename
    filename = datetime.now().strftime("%Y%m%d%H%M%S") +  fileinfo[-1]
    return filename


@backend.route("/hello/", methods = ("GET", ))
def hello():
    return 'hello, world, ok.'

#
@backend.route('/', methods = ("GET", ))  #  /admin  ---> /admin/index/
def index():
    print('this is index enter.')
    return redirect('/admin/index/')


@backend.route('/index/', methods=('GET',))  # /admin/index
@backend.route('/index/<int:page>/', methods=('GET',))  #/admin/index/2/
def admin(page=None):
    if page is None:
        page = 1
    from apps.models import News
    page_data = News.query.filter().order_by(News.created_at.desc()).paginate(page=page, per_page=4)
    return render_template('admin/index.html', page_data = page_data)


@backend.route('/add/', methods=('GET', 'POST'))
def add():
    from apps.admin.forms import NewsForm
    from apps.models import News
    from apps import db, app
    form = NewsForm()
    if form.validate_on_submit():  #表单校验
        #image_url = form.img_url.data.filename
        image_url_file = secure_filename(form.img_url.data.filename)
        ch_image_url = change_filename(image_url_file)
        image_url = app.config["UP_DIR"] + ch_image_url
        form.img_url.data.save(image_url)

        new_obj = News(
            title = form.title.data,
            content = form.content.data,
            types = form.types.data,
            img_url = '/static/img/news/' + ch_image_url,
            created_at = datetime.now(),
        )
        db.session.add(new_obj)
        db.session.commit()
        print("新增新闻成功！")
        #flash('新增新闻成功！')
        return redirect(url_for('admin.index'))
    return render_template('admin/add.html', form=form)


@backend.route('/update/<int:pk>/', methods=('GET', 'POST'))
def update(pk):
    from apps.admin.forms import NewsForm
    from apps.models import News
    from apps import db
    new_obj = News.query.get(pk)
    if not new_obj:
        return redirect(url_for('admin'))
    form = NewsForm(obj = new_obj)

    if form.validate_on_submit():  # 表单校验, 数据更新操作
        new_obj.title = form.title.data
        new_obj.content = form.content.data
        new_obj.types = form.types.data

        db.session.query(News).filter_by(id=pk).update({'title':new_obj.title,
                                                               'content':new_obj.content,
                                                               'types':new_obj.types})
        db.session.commit()
        return redirect(url_for('admin.index'))
    return render_template('admin/update.html', form = form)


@backend.route('/delete/<int:pk>/', methods=('GET', 'POST'))
def delete(pk):
    from apps.models import News
    from apps import db
    new_obj = News.query.get(pk)
    if not new_obj:
        return 'error'
    db.session.query(News).filter_by(id=pk).delete()
    db.session.commit()
    return 'ok'

apps/home/__init__.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:19' 

from flask import Blueprint

front = Blueprint("home", __name__)

import apps.home.views

apps/home/views.py
# -*- coding: utf-8 -*-  
__author__ = 'zhougy'
__date__ = '2018/8/1 下午2:20' 


from flask import Response, render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash

from . import front

from functools import wraps

#登录装饰器
def check_user_login(func):
	@wraps(func)
	def decorated_function(*args, **kwargs):
		if "user" not in session:
			return redirect(url_for("home.home_login"))
		return func(*args, **kwargs)
	return decorated_function


'''
子模块的逻辑处理函数，都是注册到当前子模块蓝图上（通过子模块蓝图注册到app上，来统一的启动服务）
'''
@front.route('/index')
def index():
	'''
    前端新闻首页
    :return:
    '''
	from apps.models import News
	news_list = News.query.filter().order_by(News.created_at.desc())
	return render_template('home/index.html', news_list=news_list)



@front.route('/cat/<name>/')
def cat(name):
	'''
    新闻类别
    :param name:
    :return:
    '''
	#查询类别为name的新闻数据
	from apps.models import News
	news_list = News.query.filter(News.types == name)
	return render_template('home/cat.html', name=name, news_list=news_list)



@front.route('/detail/<int:pk>/')
def detail(pk):
	'''
    新闻详情信息
    :param pk:
    :return:
    '''
	from apps.models import News
	new_obj = News.query.get(pk)
	return render_template('home/detail.html', pk=pk, new_obj=new_obj)

apps/templates/home/cat.html
{% extends 'home/home_base.html' %}
{% block head %}
<title>新闻类别页</title>
{% endblock %}
{% block content %}
<h3>新闻类别>{{ name }}</h3>
{% for obj in news_list %}
<div class="list-news">
    <div class="img-content">
        <img src="{{ obj.img_url }}" alt="图片">
    </div>
    <div class="right-content">
        <h3><a href="{{ url_for('home.detail', pk=obj.id) }}" >{{ obj.title }}</a></h3>
        <small>{{ obj.created_at }}</small>
    </div>
</div>
{% endfor %}
{% endblock %}

apps/templates/home/detail.html
{% extends 'home/home_base.html' %}
{% block head %}
<title>新闻详情页</title>
{% endblock %}
{% block content %}
<h3>{{ new_obj.title }}</h3>
  <div class="img-content">
            <img src="{{ new_obj.img_url }}" alt="图片">
        </div>
<p>{{ new_obj.content }}</p>
{% endblock %}

apps/templates/home/home_base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css', _external=True) }}">
    {% block head %}
    <title>首页</title>
    {% endblock %}
</head>
<body>
<!-- 页面头部 -->
<header>
    <nav>
        <ul>
            <li><a href="{{ url_for('home.index') }}">首页</a></li>
            <li><a href="{{ url_for('home.cat', name='推荐') }}">推荐</a></li>
            <li><a href="{{ url_for('home.cat', name='百家') }}">百家</a></li>
            <li><a href="{{ url_for('home.cat', name='本地') }}">本地</a></li>
            <li><a href="{{ url_for('home.cat', name='图片') }}">图片</a></li>
        </ul>
    </nav>
</header>
<!-- /页面头部 -->
<!-- 新闻内容部分 -->
<article>
   {% block content %}
  <!-- 内容区域 -->
  {% endblock  %}
</article>
<!-- /新闻内容部分 -->
{% block extrajs %}
<!-- 其它脚本 -->
{% endblock  %}
</body>
</html>

apps/templates/home/index.html
{% extends 'home/home_base.html' %}
{% block content %}
    {% for obj in news_list %}
    <div class="list-news">
        <div class="img-content">
            <img src="{{ obj.img_url }}" alt="图片">
        </div>
        <div class="right-content">
            <p><a href="{{ url_for('home.detail', pk=obj.id) }}" >{{ obj.title }}</a></p>
            <small>{{ obj.created_at }}</small>
        </div>
    </div>
    {% endfor %}
{% endblock %}